module.exports = [ 
    { item: 'Gilded full helm', level: 'hard', rarity: 'super', id: '3486' },
    { item: 'Gilded platebody', level: 'hard', rarity: 'super', id: '3481' },
    { item: 'Gilded platelegs', level: 'hard', rarity: 'super', id: '3483' },
    { item: 'Gilded plateskirt', level: 'hard', rarity: 'super', id: '3485' },
    { item: 'Gilded kiteshield', level: 'hard', rarity: 'super', id: '3488' },
    { item: 'Super potion set', level: 'hard', rarity: 'super', id: '13066' },
    { item: 'Gilded med helm', level: 'hard', rarity: 'super', id: '20146' },
    { item: 'Gilded chainbody', level: 'hard', rarity: 'super', id: '20149' },
    { item: 'Gilded sq shield', level: 'hard', rarity: 'super', id: '20152' },
    { item: 'Gilded 2h sword', level: 'hard', rarity: 'super', id: '20155' },
    { item: 'Gilded spear', level: 'hard', rarity: 'super', id: '20158' },
    { item: 'Gilded hasta', level: 'hard', rarity: 'super', id: '20161' },
    { item: 'Super restore(4)', level: 'hard', rarity: 'super', id: '3024' },
    { item: 'Super energy(4)', level: 'hard', rarity: 'super', id: '3016' },
    { item: 'Antifire potion(4)', level: 'hard', rarity: 'super', id: '2452' },
    { item: 'Rune helm (h1)', level: 'hard', rarity: 'unique', id: '10286' },
    { item: 'Rune helm (h2)', level: 'hard', rarity: 'unique', id: '10288' },
    { item: 'Rune helm (h3)', level: 'hard', rarity: 'unique', id: '10290' },
    { item: 'Rune helm (h4)', level: 'hard', rarity: 'unique', id: '10292' },
    { item: 'Rune helm (h5)', level: 'hard', rarity: 'unique', id: '10294' },
    { item: 'Rune shield (h1)', level: 'hard', rarity: 'unique', id: '7336' },
    { item: 'Rune shield (h2)', level: 'hard', rarity: 'unique', id: '7342' },
    { item: 'Rune shield (h3)', level: 'hard', rarity: 'unique', id: '7348' },
    { item: 'Rune shield (h4)', level: 'hard', rarity: 'unique', id: '7354' },
    { item: 'Rune shield (h5)', level: 'hard', rarity: 'unique', id: '7360' },
    { item: 'Rune full helm (t)', level: 'hard', rarity: 'unique', id: '2627' },
    { item: 'Rune full helm (g)', level: 'hard', rarity: 'unique', id: '2619' },
    { item: 'Rune platebody (t)', level: 'hard', rarity: 'unique', id: '2623' },
    { item: 'Rune platebody (g)', level: 'hard', rarity: 'unique', id: '2615' },
    { item: 'Rune platelegs (t)', level: 'hard', rarity: 'unique', id: '2625' },
    { item: 'Rune platelegs (g)', level: 'hard', rarity: 'unique', id: '2617' },
    { item: 'Rune plateskirt (t)', level: 'hard', rarity: 'unique', id: '3477' },
    { item: 'Rune plateskirt (g)', level: 'hard', rarity: 'unique', id: '3476' },
    { item: 'Rune kiteshield (t)', level: 'hard', rarity: 'unique', id: '2629' },
    { item: 'Rune kiteshield (g)', level: 'hard', rarity: 'unique', id: '2621' },
    { item: 'Saradomin full helm', level: 'hard', rarity: 'unique', id: '2665' },
    { item: 'Saradomin platebody', level: 'hard', rarity: 'unique', id: '2661' },
    { item: 'Saradomin platelegs', level: 'hard', rarity: 'unique', id: '2663' },
    { item: 'Saradomin plateskirt', level: 'hard', rarity: 'unique', id: '3479' },
    { item: 'Saradomin kiteshield', level: 'hard', rarity: 'unique', id: '2667' },
    { item: 'Zamorak full helm', level: 'hard', rarity: 'unique', id: '2657' },
    { item: 'Zamorak platebody', level: 'hard', rarity: 'unique', id: '2653' },
    { item: 'Zamorak platelegs', level: 'hard', rarity: 'unique', id: '2655' },
    { item: 'Zamorak plateskirt', level: 'hard', rarity: 'unique', id: '3478' },
    { item: 'Zamorak kiteshield', level: 'hard', rarity: 'unique', id: '2659' },
    { item: 'Guthix full helm', level: 'hard', rarity: 'unique', id: '2673' },
    { item: 'Guthix platebody', level: 'hard', rarity: 'unique', id: '2669' },
    { item: 'Guthix platelegs', level: 'hard', rarity: 'unique', id: '2671' },
    { item: 'Guthix plateskirt', level: 'hard', rarity: 'unique', id: '3480' },
    { item: 'Guthix kiteshield', level: 'hard', rarity: 'unique', id: '2675' },
    { item: 'Blue d\'hide body (t)', level: 'hard', rarity: 'unique', id: '7376' },
    { item: 'Blue d\'hide body (g)', level: 'hard', rarity: 'unique', id: '7374' },
    { item: 'Blue d\'hide chaps (t)', level: 'hard', rarity: 'unique', id: '7384' },
    { item: 'Blue d\'hide chaps (g)', level: 'hard', rarity: 'unique', id: '7382' },
    { item: 'Red d\'hide body (t)', level: 'hard', rarity: 'unique', id: '12331' },
    { item: 'Red d\'hide body (g)', level: 'hard', rarity: 'unique', id: '12327' },
    { item: 'Red d\'hide chaps (t)', level: 'hard', rarity: 'unique', id: '12333' },
    { item: 'Red d\'hide chaps (g)', level: 'hard', rarity: 'unique', id: '12329' },
    { item: 'Saradomin coif', level: 'hard', rarity: 'unique', id: '10390' },
    { item: 'Saradomin d\'hide', level: 'hard', rarity: 'unique', id: '10386' },
    { item: 'Saradomin chaps', level: 'hard', rarity: 'unique', id: '10388' },
    { item: 'Saradomin bracers', level: 'hard', rarity: 'unique', id: '10384' },
    { item: 'Saradomin d\'hide boots', level: 'hard', rarity: 'unique', id: '19933' },
    { item: 'Ancient coif', level: 'hard', rarity: 'unique', id: '12496' },
    { item: 'Ancient d\'hide', level: 'hard', rarity: 'unique', id: '12492' },
    { item: 'Ancient chaps', level: 'hard', rarity: 'unique', id: '12494' },
    { item: 'Ancient bracers', level: 'hard', rarity: 'unique', id: '12490' },
    { item: 'Ancient d\'hide boots', level: 'hard', rarity: 'unique', id: '19921' },
    { item: 'Armadyl coif', level: 'hard', rarity: 'unique', id: '12512' },
    { item: 'Armadyl d\'hide', level: 'hard', rarity: 'unique', id: '12508' },
    { item: 'Armadyl chaps', level: 'hard', rarity: 'unique', id: '12510' },
    { item: 'Armadyl bracers', level: 'hard', rarity: 'unique', id: '12506' },
    { item: 'Armadyl d\'hide boots', level: 'hard', rarity: 'unique', id: '19930' },
    { item: 'Bandos coif', level: 'hard', rarity: 'unique', id: '12504' },
    { item: 'Bandos d\'hide', level: 'hard', rarity: 'unique', id: '12500' },
    { item: 'Bandos chaps', level: 'hard', rarity: 'unique', id: '12502' },
    { item: 'Bandos bracers', level: 'hard', rarity: 'unique', id: '12498' },
    { item: 'Bandos d\'hide boots', level: 'hard', rarity: 'unique', id: '19924' },
    { item: 'Zamorak coif', level: 'hard', rarity: 'unique', id: '10374' },
    { item: 'Zamorak d\'hide', level: 'hard', rarity: 'unique', id: '10370' },
    { item: 'Zamorak chaps', level: 'hard', rarity: 'unique', id: '10372' },
    { item: 'Zamorak bracers', level: 'hard', rarity: 'unique', id: '10368' },
    { item: 'Zamorak d\'hide boots', level: 'hard', rarity: 'unique', id: '19936' },
    { item: 'Guthix coif', level: 'hard', rarity: 'unique', id: '10382' },
    { item: 'Guthix dragonhide', level: 'hard', rarity: 'unique', id: '10378' },
    { item: 'Guthix chaps', level: 'hard', rarity: 'unique', id: '10380' },
    { item: 'Guthix bracers', level: 'hard', rarity: 'unique', id: '10376' },
    { item: 'Saradomin d\'hide boots', level: 'hard', rarity: 'unique', id: '19927' },
    { item: 'Enchanted hat', level: 'hard', rarity: 'unique', id: '7400' },
    { item: 'Enchanted top', level: 'hard', rarity: 'unique', id: '7399' },
    { item: 'Enchanted robe', level: 'hard', rarity: 'unique', id: '7398' },
    { item: 'Saradomin stole', level: 'hard', rarity: 'unique', id: '10470' },
    { item: 'Saradomin crozier', level: 'hard', rarity: 'unique', id: '10440' },
    { item: 'Ancient stole', level: 'hard', rarity: 'unique', id: '12201' },
    { item: 'Ancient crozier', level: 'hard', rarity: 'unique', id: '12199' },
    { item: 'Armadyl stole', level: 'hard', rarity: 'unique', id: '12257' },
    { item: 'Armadyl crozier', level: 'hard', rarity: 'unique', id: '12263' },
    { item: 'Bandos stole', level: 'hard', rarity: 'unique', id: '12269' },
    { item: 'Bandos crozier', level: 'hard', rarity: 'unique', id: '12275' },
    { item: 'Zamorak stole', level: 'hard', rarity: 'unique', id: '10474' },
    { item: 'Zamorak crozier', level: 'hard', rarity: 'unique', id: '10444' },
    { item: 'Guthix stole', level: 'hard', rarity: 'unique', id: '10472' },
    { item: 'Guthix crozier', level: 'hard', rarity: 'unique', id: '10442' },
    { item: 'Black cavalier', level: 'hard', rarity: 'unique', id: '2643' },
    { item: 'Dark cavalier', level: 'hard', rarity: 'unique', id: '2641' },
    { item: 'Tan cavalier', level: 'hard', rarity: 'unique', id: '2639' },
    { item: 'White cavalier', level: 'hard', rarity: 'unique', id: '12321' },
    { item: 'Red cavalier', level: 'hard', rarity: 'unique', id: '12323' },
    { item: 'Navy cavalier', level: 'hard', rarity: 'unique', id: '12325' },
    { item: 'Robin hood hat', level: 'hard', rarity: 'unique', id: '2581' },
    { item: 'Pirate\'s hat', level: 'hard', rarity: 'unique', id: '2651' },
    { item: 'Amulet of glory (t)', level: 'hard', rarity: 'unique', id: '10362' },
    { item: 'Green dragon mask', level: 'hard', rarity: 'unique', id: '12518' },
    { item: 'Blue dragon mask', level: 'hard', rarity: 'unique', id: '12520' },
    { item: 'Red dragon mask', level: 'hard', rarity: 'unique', id: '12522' },
    { item: 'Black dragon mask', level: 'hard', rarity: 'unique', id: '12524' },
    { item: 'Pith helmet', level: 'hard', rarity: 'unique', id: '12516' },
    { item: 'Explorer backpack', level: 'hard', rarity: 'unique', id: '12514' },
    { item: 'Rune cane', level: 'hard', rarity: 'unique', id: '12379' },
    { item: 'Zombie head', level: 'hard', rarity: 'unique', id: '19912' },
    { item: 'Cyclops head', level: 'hard', rarity: 'unique', id: '19915' },
    { item: 'Nunchaku', level: 'hard', rarity: 'unique', id: '19918' },
    { item: 'Dragon boots ornament kit', level: 'hard', rarity: 'unique', id: '22231' },
    { item: '3rd age platebody', level: 'hard', rarity: '3a', id: '10348' },
    { item: '3rd age platelegs', level: 'hard', rarity: '3a', id: '10346' },
    { item: '3rd age kiteshield', level: 'hard', rarity: '3a', id: '10352' },
    { item: '3rd age range coif', level: 'hard', rarity: '3a', id: '10334' },
    { item: '3rd age range top', level: 'hard', rarity: '3a', id: '10330' },
    { item: '3rd age range legs', level: 'hard', rarity: '3a', id: '10332' },
    { item: '3rd age vambraces', level: 'hard', rarity: '3a', id: '10336' },
    { item: '3rd age mage hat', level: 'hard', rarity: '3a', id: '10342' },
    { item: '3rd age robe top', level: 'hard', rarity: '3a', id: '10338' },
    { item: '3rd age robe', level: 'hard', rarity: '3a', id: '10340' },
    { item: '3rd age amulet', level: 'hard', rarity: '3a', id: '10344' },
    { item: 'Saradomin page 1', level: 'all', rarity: 'pages', id: '3827' },
    { item: 'Saradomin page 2', level: 'all', rarity: 'pages', id: '3828' },
    { item: 'Saradomin page 3', level: 'all', rarity: 'pages', id: '3829' },
    { item: 'Saradomin page 4', level: 'all', rarity: 'pages', id: '3830' },
    { item: 'Zamorak page 1', level: 'all', rarity: 'pages', id: '3831' },
    { item: 'Zamorak page 2', level: 'all', rarity: 'pages', id: '3832' },
    { item: 'Zamorak page 3', level: 'all', rarity: 'pages', id: '3833' },
    { item: 'Zamorak page 4', level: 'all', rarity: 'pages', id: '3834' },
    { item: 'Guthix page 1', level: 'all', rarity: 'pages', id: '3835' },
    { item: 'Guthix page 2', level: 'all', rarity: 'pages', id: '3836' },
    { item: 'Guthix page 3', level: 'all', rarity: 'pages', id: '3837' },
    { item: 'Guthix page 4', level: 'all', rarity: 'pages', id: '3838' },
    { item: 'Ancient page 1', level: 'all', rarity: 'pages', id: '12621' },
    { item: 'Ancient page 2', level: 'all', rarity: 'pages', id: '12622' },
    { item: 'Ancient page 3', level: 'all', rarity: 'pages', id: '12623' },
    { item: 'Ancient page 4', level: 'all', rarity: 'pages', id: '12624' },
    { item: 'Armadyl page 1', level: 'all', rarity: 'pages', id: '12617' },
    { item: 'Armadyl page 2', level: 'all', rarity: 'pages', id: '12618' },
    { item: 'Armadyl page 3', level: 'all', rarity: 'pages', id: '12619' },
    { item: 'Armadyl page 4', level: 'all', rarity: 'pages', id: '12620' },
    { item: 'Bandos page 1', level: 'all', rarity: 'pages', id: '12613' },
    { item: 'Bandos page 2', level: 'all', rarity: 'pages', id: '12614' },
    { item: 'Bandos page 3', level: 'all', rarity: 'pages', id: '12615' },
    { item: 'Bandos page 4', level: 'all', rarity: 'pages', id: '12616' },
    { item: 'Rune full helm', level: 'hard', rarity: 'common',id: '1163' },
    { item: 'Rune platebody', level: 'hard', rarity: 'common',id: '1127' },
    { item: 'Rune platelegs', level: 'hard', rarity: 'common',id: '1079' },
    { item: 'Rune plateskirt', level: 'hard', rarity: 'common',id: '1093' },
    { item: 'Black d\'hide body', level: 'hard', rarity: 'common',id: '2503' },
    { item: 'Black d\'hide chaps', level: 'hard', rarity: 'common',id: '2497' },
    { item: 'Rune battleaxe', level: 'hard', rarity: 'common',id: '1373' },
    { item: 'Rune axe', level: 'hard', rarity: 'common',id: '1359' },
    { item: 'Rune pickaxe', level: 'hard', rarity: 'common',id: '1275' },
    { item: 'Rune dagger', level: 'hard', rarity: 'common',id: '1213' },
    { item: 'Rune longsword', level: 'hard', rarity: 'common',id: '1303' },
    { item: 'Magic shortbow', level: 'hard', rarity: 'common',id: '861' },
    { item: 'Magic longbow', level: 'hard', rarity: 'common',id: '859' },
    { item: 'Magic comp bow', level: 'hard', rarity: 'common',id: '10284' },
    { item: 'Lobster', level: 'hard', rarity: 'common', id: '379' },
    { item: 'Shark', level: 'hard', rarity: 'common', id: '385' },
    { item: 'Purple sweets', level: 'hard', rarity: 'common', id: '10476' },
    { item: 'Law rune', level: 'hard', rarity: 'common', id: '563' },
    { item: 'Nature rune', level: 'hard', rarity: 'common', id: '561' },
    { item: 'Blood rune', level: 'hard', rarity: 'common', id: '565' },
    { item: 'Blue firelighter', level: 'all', rarity: 'pages', id: '7331' },
    { item: 'Red firelighter', level: 'all', rarity: 'pages', id: '7329' },
    { item: 'Green firelighter', level: 'all', rarity: 'pages', id: '7330' },
    { item: 'White firelighter', level: 'all', rarity: 'pages', id: '10327' },
    { item: 'Purple firelighter', level: 'all', rarity: 'pages', id: '10326' },
    { item: 'Coins', level: 'all', rarity: 'pages', id: '617' }    
];