module.exports = [ 
    { item: 'Saradomin page 1', level: 'all', rarity: 'pages', id: '3827' },
    { item: 'Saradomin page 2', level: 'all', rarity: 'pages', id: '3828' },
    { item: 'Saradomin page 3', level: 'all', rarity: 'pages', id: '3829' },
    { item: 'Saradomin page 4', level: 'all', rarity: 'pages', id: '3830' },
    { item: 'Zamorak page 1', level: 'all', rarity: 'pages', id: '3831' },
    { item: 'Zamorak page 2', level: 'all', rarity: 'pages', id: '3832' },
    { item: 'Zamorak page 3', level: 'all', rarity: 'pages', id: '3833' },
    { item: 'Zamorak page 4', level: 'all', rarity: 'pages', id: '3834' },
    { item: 'Guthix page 1', level: 'all', rarity: 'pages', id: '3835' },
    { item: 'Guthix page 2', level: 'all', rarity: 'pages', id: '3836' },
    { item: 'Guthix page 3', level: 'all', rarity: 'pages', id: '3837' },
    { item: 'Guthix page 4', level: 'all', rarity: 'pages', id: '3838' },
    { item: 'Ancient page 1', level: 'all', rarity: 'pages', id: '12621' },
    { item: 'Ancient page 2', level: 'all', rarity: 'pages', id: '12622' },
    { item: 'Ancient page 3', level: 'all', rarity: 'pages', id: '12623' },
    { item: 'Ancient page 4', level: 'all', rarity: 'pages', id: '12624' },
    { item: 'Armadyl page 1', level: 'all', rarity: 'pages', id: '12617' },
    { item: 'Armadyl page 2', level: 'all', rarity: 'pages', id: '12618' },
    { item: 'Armadyl page 3', level: 'all', rarity: 'pages', id: '12619' },
    { item: 'Armadyl page 4', level: 'all', rarity: 'pages', id: '12620' },
    { item: 'Bandos page 1', level: 'all', rarity: 'pages', id: '12613' },
    { item: 'Bandos page 2', level: 'all', rarity: 'pages', id: '12614' },
    { item: 'Bandos page 3', level: 'all', rarity: 'pages', id: '12615' },
    { item: 'Bandos page 4', level: 'all', rarity: 'pages', id: '12616' },
];


