var super_rare_table = require('./super_rare');

module.exports = [ 
    { item: 'Rune helm (h1)', level: 'hard', rarity: 'unique', id: '10286' },
    { item: 'Rune helm (h2)', level: 'hard', rarity: 'unique', id: '10288' },
    { item: 'Rune helm (h3)', level: 'hard', rarity: 'unique', id: '10290' },
    { item: 'Rune helm (h4)', level: 'hard', rarity: 'unique', id: '10292' },
    { item: 'Rune helm (h5)', level: 'hard', rarity: 'unique', id: '10294' },
    { item: 'Rune shield (h1)', level: 'hard', rarity: 'unique', id: '7336' },
    { item: 'Rune shield (h2)', level: 'hard', rarity: 'unique', id: '7342' },
    { item: 'Rune shield (h3)', level: 'hard', rarity: 'unique', id: '7348' },
    { item: 'Rune shield (h4)', level: 'hard', rarity: 'unique', id: '7354' },
    { item: 'Rune shield (h5)', level: 'hard', rarity: 'unique', id: '7360' },
    { item: 'Rune full helm (t)', level: 'hard', rarity: 'unique', id: '2627' },
    { item: 'Rune full helm (g)', level: 'hard', rarity: 'unique', id: '2619' },
    { item: 'Rune platebody (t)', level: 'hard', rarity: 'unique', id: '2623' },
    { item: 'Rune platebody (g)', level: 'hard', rarity: 'unique', id: '2615' },
    { item: 'Rune platelegs (t)', level: 'hard', rarity: 'unique', id: '2625' },
    { item: 'Rune platelegs (g)', level: 'hard', rarity: 'unique', id: '2617' },
    { item: 'Rune plateskirt (t)', level: 'hard', rarity: 'unique', id: '3477' },
    { item: 'Rune plateskirt (g)', level: 'hard', rarity: 'unique', id: '3476' },
    { item: 'Rune kiteshield (t)', level: 'hard', rarity: 'unique', id: '2629' },
    { item: 'Rune kiteshield (g)', level: 'hard', rarity: 'unique', id: '2621' },
    { item: 'Saradomin full helm', level: 'hard', rarity: 'unique', id: '2665' },
    { item: 'Saradomin platebody', level: 'hard', rarity: 'unique', id: '2661' },
    { item: 'Saradomin platelegs', level: 'hard', rarity: 'unique', id: '2663' },
    { item: 'Saradomin plateskirt', level: 'hard', rarity: 'unique', id: '3479' },
    { item: 'Saradomin kiteshield', level: 'hard', rarity: 'unique', id: '2667' },
    { item: 'Zamorak full helm', level: 'hard', rarity: 'unique', id: '2657' },
    { item: 'Zamorak platebody', level: 'hard', rarity: 'unique', id: '2653' },
    { item: 'Zamorak platelegs', level: 'hard', rarity: 'unique', id: '2655' },
    { item: 'Zamorak plateskirt', level: 'hard', rarity: 'unique', id: '3478' },
    { item: 'Zamorak kiteshield', level: 'hard', rarity: 'unique', id: '2659' },
    { item: 'Guthix full helm', level: 'hard', rarity: 'unique', id: '2673' },
    { item: 'Guthix platebody', level: 'hard', rarity: 'unique', id: '2669' },
    { item: 'Guthix platelegs', level: 'hard', rarity: 'unique', id: '2671' },
    { item: 'Guthix plateskirt', level: 'hard', rarity: 'unique', id: '3480' },
    { item: 'Guthix kiteshield', level: 'hard', rarity: 'unique', id: '2675' },
    { item: 'Blue d\'hide body (t)', level: 'hard', rarity: 'unique', id: '7376' },
    { item: 'Blue d\'hide body (g)', level: 'hard', rarity: 'unique', id: '7374' },
    { item: 'Blue d\'hide chaps (t)', level: 'hard', rarity: 'unique', id: '7384' },
    { item: 'Blue d\'hide chaps (g)', level: 'hard', rarity: 'unique', id: '7382' },
    { item: 'Red d\'hide body (t)', level: 'hard', rarity: 'unique', id: '12331' },
    { item: 'Red d\'hide body (g)', level: 'hard', rarity: 'unique', id: '12327' },
    { item: 'Red d\'hide chaps (t)', level: 'hard', rarity: 'unique', id: '12333' },
    { item: 'Red d\'hide chaps (g)', level: 'hard', rarity: 'unique', id: '12329' },
    { item: 'Saradomin coif', level: 'hard', rarity: 'unique', id: '10390' },
    { item: 'Saradomin d\'hide', level: 'hard', rarity: 'unique', id: '10386' },
    { item: 'Saradomin chaps', level: 'hard', rarity: 'unique', id: '10388' },
    { item: 'Saradomin bracers', level: 'hard', rarity: 'unique', id: '10384' },
    { item: 'Saradomin d\'hide boots', level: 'hard', rarity: 'unique', id: '19933' },
    { item: 'Ancient coif', level: 'hard', rarity: 'unique', id: '12496' },
    { item: 'Ancient d\'hide', level: 'hard', rarity: 'unique', id: '12492' },
    { item: 'Ancient chaps', level: 'hard', rarity: 'unique', id: '12494' },
    { item: 'Ancient bracers', level: 'hard', rarity: 'unique', id: '12490' },
    { item: 'Ancient d\'hide boots', level: 'hard', rarity: 'unique', id: '19921' },
    { item: 'Armadyl coif', level: 'hard', rarity: 'unique', id: '12512' },
    { item: 'Armadyl d\'hide', level: 'hard', rarity: 'unique', id: '12508' },
    { item: 'Armadyl chaps', level: 'hard', rarity: 'unique', id: '12510' },
    { item: 'Armadyl bracers', level: 'hard', rarity: 'unique', id: '12506' },
    { item: 'Armadyl d\'hide boots', level: 'hard', rarity: 'unique', id: '19930' },
    { item: 'Bandos coif', level: 'hard', rarity: 'unique', id: '12504' },
    { item: 'Bandos d\'hide', level: 'hard', rarity: 'unique', id: '12500' },
    { item: 'Bandos chaps', level: 'hard', rarity: 'unique', id: '12502' },
    { item: 'Bandos bracers', level: 'hard', rarity: 'unique', id: '12498' },
    { item: 'Bandos d\'hide boots', level: 'hard', rarity: 'unique', id: '19924' },
    { item: 'Zamorak coif', level: 'hard', rarity: 'unique', id: '10374' },
    { item: 'Zamorak d\'hide', level: 'hard', rarity: 'unique', id: '10370' },
    { item: 'Zamorak chaps', level: 'hard', rarity: 'unique', id: '10372' },
    { item: 'Zamorak bracers', level: 'hard', rarity: 'unique', id: '10368' },
    { item: 'Zamorak d\'hide boots', level: 'hard', rarity: 'unique', id: '19936' },
    { item: 'Guthix coif', level: 'hard', rarity: 'unique', id: '10382' },
    { item: 'Guthix dragonhide', level: 'hard', rarity: 'unique', id: '10378' },
    { item: 'Guthix chaps', level: 'hard', rarity: 'unique', id: '10380' },
    { item: 'Guthix bracers', level: 'hard', rarity: 'unique', id: '10376' },
    { item: 'Saradomin d\'hide boots', level: 'hard', rarity: 'unique', id: '19927' },
    { item: 'Enchanted hat', level: 'hard', rarity: 'unique', id: '7400' },
    { item: 'Enchanted top', level: 'hard', rarity: 'unique', id: '7399' },
    { item: 'Enchanted robe', level: 'hard', rarity: 'unique', id: '7398' },
    { item: 'Saradomin stole', level: 'hard', rarity: 'unique', id: '10470' },
    { item: 'Saradomin crozier', level: 'hard', rarity: 'unique', id: '10440' },
    { item: 'Ancient stole', level: 'hard', rarity: 'unique', id: '12201' },
    { item: 'Ancient crozier', level: 'hard', rarity: 'unique', id: '12199' },
    { item: 'Armadyl stole', level: 'hard', rarity: 'unique', id: '12257' },
    { item: 'Armadyl crozier', level: 'hard', rarity: 'unique', id: '12263' },
    { item: 'Bandos stole', level: 'hard', rarity: 'unique', id: '12269' },
    { item: 'Bandos crozier', level: 'hard', rarity: 'unique', id: '12275' },
    { item: 'Zamorak stole', level: 'hard', rarity: 'unique', id: '10474' },
    { item: 'Zamorak crozier', level: 'hard', rarity: 'unique', id: '10444' },
    { item: 'Guthix stole', level: 'hard', rarity: 'unique', id: '10472' },
    { item: 'Guthix crozier', level: 'hard', rarity: 'unique', id: '10442' },
    { item: 'Black cavalier', level: 'hard', rarity: 'unique', id: '2643' },
    { item: 'Dark cavalier', level: 'hard', rarity: 'unique', id: '2641' },
    { item: 'Tan cavalier', level: 'hard', rarity: 'unique', id: '2639' },
    { item: 'White cavalier', level: 'hard', rarity: 'unique', id: '12321' },
    { item: 'Red cavalier', level: 'hard', rarity: 'unique', id: '12323' },
    { item: 'Navy cavalier', level: 'hard', rarity: 'unique', id: '12325' },
    { item: 'Robin hood hat', level: 'hard', rarity: 'unique', id: '2581' },
    { item: 'Pirate\'s hat', level: 'hard', rarity: 'unique', id: '2651' },
    { item: 'Amulet of glory (t)', level: 'hard', rarity: 'unique', id: '10362' },
    { item: 'Green dragon mask', level: 'hard', rarity: 'unique', id: '12518' },
    { item: 'Blue dragon mask', level: 'hard', rarity: 'unique', id: '12520' },
    { item: 'Red dragon mask', level: 'hard', rarity: 'unique', id: '12522' },
    { item: 'Black dragon mask', level: 'hard', rarity: 'unique', id: '12524' },
    { item: 'Pith helmet', level: 'hard', rarity: 'unique', id: '12516' },
    { item: 'Explorer backpack', level: 'hard', rarity: 'unique', id: '12514' },
    { item: 'Rune cane', level: 'hard', rarity: 'unique', id: '12379' },
    { item: 'Zombie head', level: 'hard', rarity: 'unique', id: '19912' },
    { item: 'Cyclops head', level: 'hard', rarity: 'unique', id: '19915' },
    { item: 'Nunchaku', level: 'hard', rarity: 'unique', id: '19918' },
    { item: 'Dragon boots ornament kit', level: 'hard', rarity: 'unique', id: '22231' },
];
