var super_rare_table = require('./super_rare');

module.exports = [ 
    { item: 'Rune helm (h1)', freq: 1, id: '10286' },
    { item: 'Rune helm (h2)', freq: 1, id: '10288' },
    { item: 'Rune helm (h3)', freq: 1, id: '10290' },
    { item: 'Rune helm (h4)', freq: 1, id: '10292' },
    { item: 'Rune helm (h5)', freq: 1, id: '10294' },
    { item: 'Rune shield (h1)', freq: 1, id: '7336' },
    { item: 'Rune shield (h2)', freq: 1, id: '7342' },
    { item: 'Rune shield (h3)', freq: 1, id: '7348' },
    { item: 'Rune shield (h4)', freq: 1, id: '7354' },
    { item: 'Rune shield (h5)', freq: 1, id: '7360' },
    { item: 'Rune full helm (t)', freq: 1, id: '2627' },
    { item: 'Rune full helm (g)', freq: 1, id: '2619' },
    { item: 'Rune platebody (t)', freq: 1, id: '2623' },
    { item: 'Rune platebody (g)', freq: 1, id: '2615' },
    { item: 'Rune platelegs (t)', freq: 1, id: '2625' },
    { item: 'Rune platelegs (g)', freq: 1, id: '2617' },
    { item: 'Rune plateskirt (t)', freq: 1, id: '3477' },
    { item: 'Rune plateskirt (g)', freq: 1, id: '3476' },
    { item: 'Rune kiteshield (t)', freq: 1, id: '2629' },
    { item: 'Rune kiteshield (g)', freq: 1, id: '2621' },
    { item: 'Saradomin full helm', freq: 1, id: '2665' },
    { item: 'Saradomin platebody', freq: 1, id: '2661' },
    { item: 'Saradomin platelegs', freq: 1, id: '2663' },
    { item: 'Saradomin plateskirt', freq: 1, id: '3479' },
    { item: 'Saradomin kiteshield', freq: 1, id: '2667' },
    { item: 'Zamorak full helm', freq: 1, id: '2657' },
    { item: 'Zamorak platebody', freq: 1, id: '2653' },
    { item: 'Zamorak platelegs', freq: 1, id: '2655' },
    { item: 'Zamorak plateskirt', freq: 1, id: '3478' },
    { item: 'Zamorak kiteshield', freq: 1, id: '2659' },
    { item: 'Guthix full helm', freq: 1, id: '2673' },
    { item: 'Guthix platebody', freq: 1, id: '2669' },
    { item: 'Guthix platelegs', freq: 1, id: '2671' },
    { item: 'Guthix plateskirt', freq: 1, id: '3480' },
    { item: 'Guthix kiteshield', freq: 1, id: '2675' },
    { item: 'Blue d\'hide body (t)', freq: 1, id: '7376' },
    { item: 'Blue d\'hide body (g)', freq: 1, id: '7374' },
    { item: 'Blue d\'hide chaps (t)', freq: 1, id: '7384' },
    { item: 'Blue d\'hide chaps (g)', freq: 1, id: '7382' },
    { item: 'Saradomin coif', freq: 1, id: '10390' },
    { item: 'Saradomin d\'hide', freq: 1, id: '10386' },
    { item: 'Saradomin chaps', freq: 1, id: '10388' },
    { item: 'Saradomin bracers', freq: 1, id: '10384' },
    { item: 'Ancient coif', freq: 1, id: '12496' },
    { item: 'Ancient d\'hide', freq: 1, id: '12492' },
    { item: 'Ancient chaps', freq: 1, id: '12494' },
    { item: 'Ancient bracers', freq: 1, id: '12490' },
    { item: 'Armadyl coif', freq: 1, id: '12512' },
    { item: 'Armadyl d\'hide', freq: 1, id: '12508' },
    { item: 'Armadyl chaps', freq: 1, id: '12510' },
    { item: 'Armadyl bracers', freq: 1, id: '12506' },
    { item: 'Bandos coif', freq: 1, id: '12504' },
    { item: 'Bandos d\'hide', freq: 1, id: '12500' },
    { item: 'Bandos chaps', freq: 1, id: '12502' },
    { item: 'Bandos bracers', freq: 1, id: '12498' },
    { item: 'Zamorak coif', freq: 1, id: '10374' },
    { item: 'Zamorak d\'hide', freq: 1, id: '10370' },
    { item: 'Zamorak chaps', freq: 1, id: '10372' },
    { item: 'Zamorak bracers', freq: 1, id: '10368' },
    { item: 'Guthix coif', freq: 1, id: '10382' },
    { item: 'Guthix dragonhide', freq: 1, id: '10378' },
    { item: 'Guthix chaps', freq: 1, id: '10380' },
    { item: 'Guthix bracers', freq: 1, id: '10376' },
    { item: 'Enchanted hat', freq: 1, id: '7400' },
    { item: 'Enchanted top', freq: 1, id: '7399' },
    { item: 'Enchanted robe', freq: 1, id: '7398' },
    { item: 'Saradomin stole', freq: 1, id: '10470' },
    { item: 'Saradomin crozier', freq: 1, id: '10440' },
    { item: 'Ancient stole', freq: 1, id: '12201' },
    { item: 'Ancient crozier', freq: 1, id: '12199' },
    { item: 'Armadyl stole', freq: 1, id: '12257' },
    { item: 'Armadyl crozier', freq: 1, id: '12263' },
    { item: 'Bandos stole', freq: 1, id: '12269' },
    { item: 'Bandos crozier', freq: 1, id: '12275' },
    { item: 'Zamorak stole', freq: 1, id: '10474' },
    { item: 'Zamorak crozier', freq: 1, id: '10444' },
    { item: 'Guthix stole', freq: 1, id: '10472' },
    { item: 'Guthix crozier', freq: 1, id: '10442' },
    { item: 'Black cavalier', freq: 1, id: '2643' },
    { item: 'Dark cavalier', freq: 1, id: '2641' },
    { item: 'Tan cavalier', freq: 1, id: '2639' },
    { item: 'Robin hood hat', freq: 1, id: '2581' },
    { item: 'Pirate\'s hat', freq: 1, id: '2651' },
    { item: 'Amulet of glory (t)', freq: 1, id: '10362' },
    super_rare_table
];
